### ISSUE TITLE
Caveat for proc-macro-crate

### ISSUE THREAD

**Issue by dtolnay** [MaulingMonkey/rust-reviews#71]
I don't share your positive review of proc-macro-crate -- it is built on parsing Cargo.toml so it would break using anything downstream in a non-Cargo environment, like a Bazel-based monorepo or some linux distros. Consider adding a caveat to discourage using proc-macro-crate. For example it would be totally inappropriate for something like the `futures` crate to rely on proc-macro-crate.

**Comment by MaulingMonkey** [comment]
Is there a superior alternative you can point me towards?

Right now I'm aware of three options - the last being "use proc-macro-crate with a hardcoded fallback" - which seems strictly superior than hardcoding the crate name.  Which still doesn't handle non-Cargo renames, but I'm unaware of anything that currently does.

This might call for improved documentation on proc-macro-crate's part (to recommend better patterns), or hint at some possible API improvements (perhaps proc-macro-crate should fall back on a hardcoded default if Cargo.toml is missing or something?), but the crate itself still seems like a solid option for now.

*EDIT:*  Or maybe Rust itself landed a `$crate` equivalent for proc macros and this entire crate can be considered legacy/deprecated/???

### Hardcode the original crate name

```rust
let name = "my_crate";
let ident = Ident::new(&name, Span::call_site());
```

|   | Original | Renamed
| --- | --- | --- |
| Cargo | ✔️ | ❌ compile error |
| Bazel |  ✔️ | ❌ compile error |

### Use proc-macro-crate per their examples

```rust
let name = crate_name("my-crate").expect("my-crate is present in `Cargo.toml`");
let ident = Ident::new(&name, Span::call_site());
```

|   | Original | Renamed
| --- | --- | --- |
| Cargo | ✔️ | ✔️ |
| Bazel |  ❌ macro panic | ❌ macro panic |

### Use proc-macro-crate with a hardcoded fallback

```rust
let name = crate_name("my-crate").unwrap_or("my_crate".to_string());
let ident = Ident::new(&name, Span::call_site());
```

|   | Original | Renamed
| --- | --- | --- |
| Cargo | ✔️ | ✔️ |
| Bazel |  ✔️ | ❌ macro panic |

**Comment by dtolnay** [comment]
For bang macros the preferred way is a shim that passes a $crate token to the proc macro.

##### repro/Cargo.toml

```toml
[package]
name = "repro"
version = "0.0.0"
edition = "2018"

[dependencies]
my-futures = { package = "futures", path = "../futures" }
```

##### repro/src/main.rs

```rust
// expands to `type ItWorked = futures::T;`
my_futures::select!(x y z);

fn main() {
    let _: ItWorked;
}
```

##### futures/Cargo.toml

```toml
[package]
name = "futures"
version = "0.0.0"
edition = "2018"

[dependencies]
futures-macro = { path = "../futures-macro" }
```

##### futures/src/lib.rs

```rust
#[doc(hidden)]
pub use futures_macro;

#[macro_export]
macro_rules! select {
    ($($args:tt)*) => {
        $crate::futures_macro::select!{$crate $($args)*}
    };
}

pub struct T;
```

##### futures-macro/Cargo.toml

```toml
[package]
name = "futures-macro"
version = "0.0.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
```

##### futures-macro/src/lib.rs

```rust
use proc_macro::TokenStream;
use quote::quote;

#[proc_macro]
pub fn select(input: TokenStream) -> TokenStream {
    let input = proc_macro2::TokenStream::from(input);

    let mut tokens = input.into_iter();
    let futures = tokens.next().unwrap();
    eprintln!("input = {:#?}", tokens.collect::<proc_macro2::TokenStream>());

    TokenStream::from(quote! {
        type ItWorked = #futures::T;
    })
}
```

For attribute macros, someone needs to write a $crate RFC. -.-
